### ISSUE TITLE
Project maintenance

### ISSUE THREAD

**Issue by SimonSapin** [scrapy/cssselect#48]
I’m not really interested in cssselect anymore. I think the approach of "translating" selectors to XPath is fundamentally flawed (see #12 for example). I’ve started [cssselect2](https://github.com/SimonSapin/cssselect2) which implements Selectors "for real", but it’s blocked on a [deciding what kind of tree it works on](https://github.com/SimonSapin/cssselect2/issues/1).

I’ve also kind of moved on from Python; I mostly work with Rust nowadays.

Still, some people seem to be interested in cssselect. @redapple, @Dobz, @kmike, @bukzor, @sjp, @kovidgoyal, or anyone, would you be interested in maintaining it? I can give push access to this repository and to PyPI.

**Comment by arthru** [comment]
Would it be possible to have a time during which you would train me on that ? I use the lib but never hacked on it...

**Comment by SimonSapin** [comment]
I can answer questions about how things work internally (maybe start by reading the code, it’s not very big), but maintenance is mostly about triaging, responding to bug reports, and reviewing and merging (or rejecting) pull requests.

**Comment by arthru** [comment]
So after a quick review on pull requests and issues, I noticed some links to implementations in cssselect2 and lselect. What is the status of these projects ? How does it involve cssselect ?

**Comment by SimonSapin** [comment]
See the first paragraph of this issue :) lselect is the previous name of cssselect2, they’re essentially the same project.

**Comment by redapple** [comment]
@SimonSapin , are you still open to giving admin rights to other people for maintenance?
myself and other [scrapy](https://github.com/scrapy/scrapy) devs are interested in continuing work on cssselect

**Comment by SimonSapin** [comment]
@redapple sounds good. I may be best to move this repo under https://github.com/scrapy/ , what do you think? Though I’d apparently need some permissions in the org to do that transfer.

**Comment by redapple** [comment]
Sounds good @SimonSapin . 
If I read https://help.github.com/articles/about-repository-transfers/ well, it seems that if you request the transfer, we'll receive an email to accept.
I've also created a "cssselect maintenance" team https://github.com/orgs/scrapy/teams/cssselect-maintenance that I believe you can request membership to (somehow I cannot add you directly)
That GitHub help page also mentions you'd still be a collaborator for the repo

**Comment by redapple** [comment]
hm, right, https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/ also says

> Users must have admin or owner permissions within the receiving organization before they can transfer a repository that they individually own.

**Comment by redapple** [comment]
@SimonSapin , we've sent you an invite for https://github.com/orgs/scrapy/teams/cssselect-maintenance
Let's see if it's sufficient to be able to initiate transfer

**Comment by redapple** [comment]
Thanks @SimonSapin for transferring the repo to Scrapy org.

We created a [team on GitHub](https://github.com/orgs/scrapy/teams/cssselect) so anyone interested in joining the effort can contact the team maintainers to get added
