### ISSUE TITLE
Encoding Error using utf8

### ISSUE THREAD

**Issue by spac3-monkey** [scrapy/cssselect#54]
In code `# coding: utf8` alias should be replaced with the actual encoding `# -*- encoding: utf-8 -*-`

**Comment by redapple** [comment]
@spac3-monkey ,
https://docs.python.org/3/tutorial/interpreter.html#source-code-encoding recommends `# -*- coding: utf-8 -*-`
that's what I changed in https://github.com/scrapy/cssselect/issues/55
would that work for you?

**Comment by spac3-monkey** [comment]
@redapple yes, thanks!!

**Comment by redapple** [comment]
Closed with #55
