### ISSUE TITLE
Move docs to readthedocs

### ISSUE THREAD

**Issue by redapple** [scrapy/cssselect#65]
Procedure to build and upload docs to https://pythonhosted.org/cssselect/ used to be:

```
(pip install sphinx)
python setup.py build_sphinx
python setup.py upload_sphinx
```

But now you get:

```
$ python setup.py upload_sphinx
running upload_sphinx
Submitting documentation to https://upload.pypi.org/legacy/
Upload failed (410): Uploading documentation is no longer supported, we recommend using https://readthedocs.org/.
```

For 1.0.0, I had to manually create the zip file from the docs _build/html folder and upload it with PyPI's web interface.

**Comment by kmike** [comment]
Google may suggst pythonhosted docs for a long time after we deprecate them; I think we should add a warning on each page that docs are moved, and upload a new zip file after moving to rtfd. Or just create a redirect. I had this problem with one of my packages, and even after a couple of years many people are coming from these 'warning' links to the new docs.

**Comment by liZe** [comment]
As there's no way to remove the documentation from pythonhosted, the "officially suggested way" used by many projects is to replace the documentation by a redirection in HTML, something like:

```html
<html>
    <head>
        <title>xxx has moved</title>
        <meta http-equiv="refresh" content="1; URL=http://xxx.readthedocs.io/">
        <meta name="keywords" content="automatic redirection">
    </head>
    <body>
        xxx's documentation is maintained elsewhere.
        You will be redirected to the new documentation within 1 second.
        If the browser does not automatically redirect you, you may want to go to
        <a href="http://xxx.readthedocs.io/">xxx's documentation</a> manually.
    </body>
</html>
```

**Comment by redapple** [comment]
Thanks @liZe . I just did that, and https://pythonhosted.org/cssselect/ now redirects to https://cssselect.readthedocs.io/
