### ISSUE TITLE
Support for "matches-any" pseudo-class :matches()

### ISSUE THREAD

**Issue by redapple** [scrapy/cssselect#67]
[CSS Selectors Level 4 (draft)](https://drafts.csswg.org/selectors-4/#matches) proposes the `:matches()` pseudo-class (apparently inspired by [`:any()` already supported in some browsers](http://caniuse.com/#search=%3Aany))

Example from https://www.sitepoint.com/css-selectors-level-4-the-path-to-css4/

> `div:matches(.active, .visible, #main)`

There can be a need for _or_ relations on XPath predicates and `:matches()` could allow that.

**Comment by wRAR** [comment]
Note that https://drafts.csswg.org/selectors-4/#matches now says that the pseudo-class should be `:is()`, while `:matches()` can be supported as an obsolete alias.

**Comment by wRAR** [comment]
Fixed in #109
