### ISSUE TITLE
A nasty bug lies within the library

### ISSUE THREAD

**Issue by vahidhashemi** [scrapy/cssselect#77]
Have a crawler based on this  library cssselect (1.0.0) my customer was nagging about not getting all the news he wanted for quite sometimes.
Had a closer look and found something peculiar.

If you want to reproduce the error simply go to this url :
http://www.bbc.com/news/uk-england-40465494
and try this selector : 
.story-body__inner > p

the purpose of mentioned selector is to get news body and when it will get to following line :

> Mr Paget-Brown resigned following sustained criticism of the council and an aborted meeting of its cabinet on Thursday, from which leaders had tried to ban members of the public and press.

it only get the 

> Mr Paget-Brown

You can take a look at this picture which I got from crawler
http://imgur.com/a/4UcMb

I have tested my selector using firepath in firefox

**Comment by redapple** [comment]
This is what cssselect translates your selector to:
```
>>> from cssselect import GenericTranslator
>>> expression = GenericTranslator().css_to_xpath('.story-body__inner > p')
>>> expression
"descendant-or-self::*[@class and contains(concat(' ', normalize-space(@class), ' '), ' story-body__inner ')]/p"
```
When applying this XPath in Chrome, I get 36 results for the sample page you linked to:

![image](https://user-images.githubusercontent.com/886296/27760728-103ff0d8-5e4f-11e7-92e2-3884485003d0.png)

I get the same 36 results with the CSS selector in Chrome:

![image](https://user-images.githubusercontent.com/886296/27760739-546bddda-5e4f-11e7-89c7-db669d6d61d1.png)

When using this translated XPath with lxml for example, I also get 36 results:
```
>>> from lxml.html import fromstring
>>> doc = fromstring(r.text)
>>> doc.xpath("descendant-or-self::*[@class and contains(concat(' ', normalize-space(@class), ' '), ' story-body__inner ')]/p")
[<Element p at 0x7f4958dd67c8>, <Element p at 0x7f4958dd6c78>, <Element p at 0x7f49585fb6d8>, <Element p at 0x7f49585fb728>, <Element p at 0x7f49585fb778>, <Element p at 0x7f49585fb7c8>, <Element p at 0x7f49585fb818>, <Element p at 0x7f49585fb868>, <Element p at 0x7f49585fb8b8>, <Element p at 0x7f49585fb908>, <Element p at 0x7f49585fb958>, <Element p at 0x7f49585fb9a8>, <Element p at 0x7f49585fb9f8>, <Element p at 0x7f49585fba48>, <Element p at 0x7f49585fba98>, <Element p at 0x7f49585fbae8>, <Element p at 0x7f49585fbb38>, <Element p at 0x7f49585fbb88>, <Element p at 0x7f49585fbbd8>, <Element p at 0x7f49585fbc28>, <Element p at 0x7f49585fbc78>, <Element p at 0x7f49585fbcc8>, <Element p at 0x7f49585fbd18>, <Element p at 0x7f49585fbd68>, <Element p at 0x7f49585fbdb8>, <Element p at 0x7f49585fbe08>, <Element p at 0x7f49585fbe58>, <Element p at 0x7f49585fbea8>, <Element p at 0x7f49585fbef8>, <Element p at 0x7f49585fbf48>, <Element p at 0x7f49585fbf98>, <Element p at 0x7f4958602048>, <Element p at 0x7f4958602098>, <Element p at 0x7f49586020e8>, <Element p at 0x7f4958602138>, <Element p at 0x7f4958602188>]
>>> len(doc.xpath("descendant-or-self::*[@class and contains(concat(' ', normalize-space(@class), ' '), ' story-body__inner ')]/p"))
36
>>> 
```

I believe your issue is more about how you use the library within your crawler to extract data from pages.

**Comment by vahidhashemi** [comment]
Thanks for your thorough  answer but I already got what you are doing inside my crawler.

http://imgur.com/a/YoeKt <-- shows I got 33 elements
and
http://imgur.com/a/NLORN <-- shows that paragraph is incomplete!

Problem is not knowing how to work with selectors/xpath, the problem is when I get to 5th p the cssselector only throw back 

> Mr Paget-Brown

which is not acceptable. What I need is something like this : 
`<p>Mr Paget-Brown <a href="http://www.bbc.co.uk/news/uk-england-40461581" class="story-body__link">resigned following sustained criticism of the council</a> and an aborted meeting of its cabinet on Thursday, from which leaders had tried to ban members of the public and press.</p>`

This is what a select should do. I can't tailor my crawler for every single website out there.

**Comment by redapple** [comment]
> when I get to 5th p the cssselector only throw back "Mr Paget-Brown"

cssselect is used only for translating CSS to XPath. I believe (strongly) that 
```
descendant-or-self::*[@class and contains(concat(' ', normalize-space(@class), ' '), ' story-body__inner ')]/p ```
is a correct translation of `.story-body__inner > p`

If the CSS or XPath engine used in your crawler does not provide you with the the "full" `<p>` element when you use this XPath translation, then it's a problem with the CSS/XPath engine, not an issue with `cssselect`

**Comment by vahidhashemi** [comment]
That doesn't make sense. Just because CSS is translating to XPATH there should be some losses. Also I'm using lxml to translating the html to graph-like entity. Is there any other option available rather than lxml?

**Comment by redapple** [comment]
You are misinterpreting what  `.text` gives you from an lxml `Element`.

```
>>> doc = fromstring('''<p>Mr Paget-Brown <a href="http://www.bbc.co.uk/news/uk-england-40461581" class="story-body__link">resigned following sustained criticism of the council</a> and an aborted meeting of its cabinet on Thursday, from which leaders had tried to ban members of the public and press.</p>''')
>>> doc.xpath('//p')
[<Element p at 0x7f49585fb728>]
>>> p = doc.xpath('//p')[0]
```

Accessing `.text` will only get you the first text child, not descendants (here, the text child of the nested `<a>`)
```
>>> p.text, p.tail
('Mr Paget-Brown ', None)
```
The rest of the text you are after are in fact `.text` and `.tail` of the nested `<a>`:

```
>>> a = p.xpath('a')[0]
>>> a.text, a.tail
('resigned following sustained criticism of the council', ' and an aborted meeting of its cabinet on Thursday, from which leaders had tried to ban members of the public and press.')
```

See [lxml's docs on that.](http://lxml.de/tutorial.html#elements-contain-text)

If you want to get all text within the paragraph, whetever their depth, you can use either `.//text()`, or an XPath's string function like `normalize-space()`

```
>>> p.xpath('.//text()')
['Mr Paget-Brown ', 'resigned following sustained criticism of the council', ' and an aborted meeting of its cabinet on Thursday, from which leaders had tried to ban members of the public and press.']

>>> p.xpath('string()')
'Mr Paget-Brown resigned following sustained criticism of the council and an aborted meeting of its cabinet on Thursday, from which leaders had tried to ban members of the public and press.'

```

**Comment by vahidhashemi** [comment]
One fundamental question. Is this cssselector's github or lxml? as a matter of fact I don't want to use lxml I want to use cssselector and apparently cssselector has issue according to nsested paraghraps with hrefs'.

This is what I expected from a CSS selector if you get to a point that your paragraph is nested with other elements throws those elements to me I will clean them afterward. But the csselector doesn't do that at the moment. Don't you agree? if so, please open this issue. So we can follow up this bug.

**Comment by redapple** [comment]
`cssselect` has only one purpose: translating a CSS3 selector to an equivalent XPath location path.

`.story-body__inner > p` is a class selector followed by a [child combinator](https://www.w3.org/TR/css3-selectors/#child-combinators) for a `p` element.

`cssselect` translates that to XPath following the [CSS3 definitions](https://www.w3.org/TR/css3-selectors/#selectors):

> E > F	: an F element child of an E element

The current implementation of `cssselect` translates this to `descendant-or-self::*[@class and contains(concat(' ', normalize-space(@class), ' '), ' story-body__inner ')]/p` which is a correct translation.

`.story-body__inner > p` should return `p` elements (and not text content from these elements), as your Chrome dev tools and Firepath show.

`lxml` is _one_ library that understands XPath. And it also selects `p` elements for the XPath translation from `cssselect` with your sample HTML document. What you do with those `p` elements is another thing. It's not `cssselect`'s job.

So no, I do not agree that this is a bug in `cssselect` that the lxml-selected `p` elements do not produce their text content using the `.text` attribute.
Feel free to open a bug on `lxml` if you want to change how to access text content from elements.
Currently, [`.text` on an element is defined as](http://lxml.de/api/lxml.etree._Element-class.html):

> text
> Text before the first subelement. This is either a string or the value None, if there was no text.

which is what you are getting.
