### ISSUE TITLE
selector has problem when getting to paraghpes nested with href

### ISSUE THREAD

**Issue by vahidhashemi** [scrapy/cssselect#78]
According to this issue : https://github.com/scrapy/cssselect/issues/77

I still think the selector is not capable of handling proper selector in some situation.

reason to open another issue : the last one closed just because of not reading the whole issue thoroughly!

**Comment by redapple** [comment]
> the last one closed just because of not reading the whole issue thoroughly!

This is not the case. See my last comment in #77 . cssselect's job to translate CSS to XPath works correctly in the case you provided.

**Comment by redapple** [comment]
If you can provide an example where cssselect provided you with an incorrect translation from CSS to XPath, we'll be happy to investigate.

**Comment by vahidhashemi** [comment]
this is what I get from following selector in firefox using firepath : 
http://imgur.com/a/prDY4
But the cssselector doesn't give me the same answer.

**Comment by redapple** [comment]
Same as #77 .
`cssselect` correctly translates the CSS selector from #77 .
