### ISSUE TITLE
The PyPI tarball doesn't include tests

### ISSUE THREAD

**Issue by wRAR** [scrapy/cssselect#92]
I guess MANIFEST.in needs to be updated, like https://github.com/scrapy/parsel/blob/master/MANIFEST.in

**Comment by Gallaecio** [comment]
Hmm… Do we want tests included in the PyPI tarball? (I know, I’m saying this a month after a pull request in that direction…)

**Comment by wRAR** [comment]
I learned since filing this report that at least some other people prefer keeping tests in the repo but not in the PyPI tarball so I don't know what is the accepted best practice.
